Add Django email channel
openedx/edx-ace pull request #25
Opened 2018-01-17 19:14 UTC by OmarIthawi

**Description:** This PR adds `send_mail()` function from Django to ACE as an alternative to Sailthru. This is a follow up to my email PR (https://github.com/edx/edx-platform/pull/16545).

**Merge deadline:** I have no deadline, but https://github.com/edx/edx-platform/pull/16545 has been going on for a while, so I'd really appreciate it to speed this up.

**Installation instructions:** Please do `pip install -e .` to have the new entry points installed.
instructions.

**Testing instructions:**
Not sure how to test this standalone, but generally to send a message the following needs to be configured:

```python
ACE_CHANNEL_DEFAULT_EMAIL=u'file_email',
ACE_CHANNEL_TRANSACTIONAL_EMAIL=u'django_email',
ACE_ENABLED_CHANNELS=[u'django_email', u'file_email'],
```

**Reviewers:**
- [x] @mulby 

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [x] Version bumped
- [ ] ~~Changelog record added~~
     * Too much missing changelogs to trackback. Out of the scope of this PR.
- [x] Documentation updated (not only docstrings)
- [x] Commits are squashed
- [x] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:**
 - [x] I'm not totally happy with `ACE_CHANNEL_DJANGO_FROM_ADDRESS_GETTER`, but it works OK for now. If you have any suggestions please let me know!
   * Replaced with `message.options['from_email']`
 - [x] Is `django_email` the correct name? 
   * Looks like it.

2018-01-17 19:14 UTC, edx-webhook commented
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2151](https://openedx.atlassian.net/browse/OSPR-2151) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ace/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-01-17 19:27 UTC, nasthagiri commented
FYI @edx/educator-neem

2018-01-17 21:23 UTC, nasthagiri commented
@OmarIthawi Thanks for this PR.  @mulby will review it for us.

2018-01-18 12:19 UTC, OmarIthawi commented
Thanks Nimisha! Looking forward to it @mulby!

2018-01-23 15:27 UTC, mulby requested changes
Overall, I love the idea, I suggested a couple of fundamental changes, however, to the structure of this. Let me know what you think!

2018-01-23 15:27 UTC, mulby commented on edx_ace/channel/django.py
> +        return True
Does send_email() work without any configuration? If not, I think this method should ensure that the required configuration values are set.

2018-01-23 15:27 UTC, mulby commented on edx_ace/channel/sailthru.py
> +                render_to_string(u'ace_common/edx_ace/sailthru/beacon.html')
This won't work if this library is used outside of the LMS. I would prefer the alternative solution I proposed in https://github.com/edx/edx-platform/pull/16545 that passes the channel into the template.

2018-01-23 15:27 UTC, mulby commented on edx_ace/channel/django.py
> +        html_message = rendered_message.body_html.replace(
As I mentioned on https://github.com/edx/edx-platform/pull/16545, I think we should try to figure out a way to avoid this type of thing.

2018-01-23 15:27 UTC, mulby commented on edx_ace/channel/django.py
> +                get_from_address(),
I would love to replace this with something like:

```
from_address = message.options.get('from_address')
if from_address is None:
    raise FatalChannelDeliveryError('From address must be included in message delivery options')
```

2018-02-22 15:57 UTC, OmarIthawi commented
@mulby @nasthagiri I've merged both of #26 and #25 and now it's ready for review.

`codecov` isn't happy about the untested new paths, so I'm adding the missing tests, meanwhile.

2018-03-16 21:16 UTC, OmarIthawi commented on edx_ace/channel/django.py
> +        return True
@mulby `send_mail` usually works out of the box, given an smtp server is setup in localhost. Otherwise the server has to be configured. So it is reasonable to assume that it's going to work anyway:

```
from django.conf import settings
from django.core.mail import send_mail

settings.configure()

send_mail(subject='Hi', message='hello!', from_email='i@omardo.com', recipient_list=['i@omardo.com'])
```

The above expects a localhost smtp server, and fails otherwise. Since it's impractical to check for SMTP, I think it's better to keep it as a and assume it's enabled all the time.

2018-03-16 21:41 UTC, OmarIthawi commented on edx_ace/channel/django.py
> +                get_from_address(),
@mulby done! Thanks for the suggestion.

2018-03-17 13:01 UTC, mulby reviewed
Overall this is looking really good. Just a few suggestions sprinkled in here.

Thanks for taking the time to contribute this!

2018-03-17 13:01 UTC, mulby commented on edx_ace/channel/__init__.py
> +    def action_links(self):
I don't think we should include these in the `Channel` base class. If anything we could create an `EmailChannel`  base class that contains them, but I suspect they won't be relevant to all channel types.

If, for whatever reason, a channel was passed into the template that didn't define these properties, I think Django would handle that gracefully, but it's probably worth having a test case for.

2018-03-17 13:01 UTC, mulby commented on edx_ace/channel/__init__.py
> +    channel_map = defaultdict(dict)
We may want to do something a bit more structured here. I hacked together this dictionary of dictionaries, but defining a very simple class probably makes more sense.

```
class ChannelMap(object):

    def __init__(self):
        self.channel_type_to_channel_impl = defaultdict(OrderedDict)

    def register_channel(channel, channel_name):
        self.channel_type_to_channel_impl[channel.channel_type][channel_name] = channel

    def get_channel(channel_type, channel_name):
        try:
            return self.channel_type_to_channel_impl[channel_type][channel_name]
        except KeyError:
            return self.get_default_channel(channel_type)

    def get_default_channel(channel_type):
        try:
            return six.next(six.itervalues(self.channel_type_to_channel_impl[channel_type]))
         except StopIteration, KeyError:
            raise UnsupportedChannelError("...")
```

I think that would help clarify the structure of the channel map.

2018-03-17 13:01 UTC, mulby commented on edx_ace/channel/django.py
> +# -*- coding: utf-8 -*-
I think we should actually call this module something like "django_email" since "django" is such a broad framework.

2018-03-17 13:01 UTC, mulby commented on edx_ace/channel/django.py
> +        return True
Got it, makes sense!

We also may want to point people at the EMAIL_BACKEND setting so that they could test this using console output or a file or something:

```
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
```

2018-03-17 13:01 UTC, mulby commented on edx_ace/channel/django.py
> +        from_address = message.options.get(u'from_address')
I like this a lot better! Great work.

2018-03-17 13:01 UTC, mulby commented on edx_ace/channel/django.py
> +        except SMTPException as e:
Is this the only type of exception that can be raised here?

2018-03-17 13:01 UTC, mulby commented on edx_ace/renderers.py
> +             channel (Channel)
Oops, we should fill out these doc strings.

2018-03-17 13:01 UTC, mulby commented on edx_ace/tests/test_ace.py
> +    @patch(u'edx_ace.renderers.loader.get_template')
I'm surprised this second patch is needed... doesn't the UnsupportedChannelError get raised first?

2018-03-17 13:01 UTC, mulby commented on edx_ace/tests/test_channel.py
> +class TestAce(TestCase):
Maybe name this "TestChannelMap" or something similar?

2018-03-17 13:01 UTC, mulby commented on edx_ace/tests/test_channel.py
> +    def test_get_channel_for_channel_type(self):
I would also test the case when only a single channel implementation is registered for a particular channel type and we have to use the "six.next()" stuff.

2018-03-17 13:01 UTC, mulby commented on edx_ace/tests/test_delivery.py
> +            get_channel_for_channel_type(ChannelType.PUSH, self.message)
I think you can probably just get rid of this test case since you are testing this scenario here:

https://github.com/edx/edx-ace/pull/25/files#diff-29dfc83ce52b632360428f45bae41948R55

2018-03-17 13:17 UTC, OmarIthawi commented on edx_ace/tests/test_channel.py
> +class TestAce(TestCase):
Done

2018-03-17 13:20 UTC, OmarIthawi commented on edx_ace/channel/django.py
> +# -*- coding: utf-8 -*-
Done

2018-03-19 05:32 UTC, OmarIthawi commented on edx_ace/renderers.py
> +             channel (Channel)
Done

2018-04-10 09:42 UTC, OmarIthawi commented
@nedbat @mulby Just wanted to let you know that I'm taking a final review at this PR to see what's missing. Should be ready by the end of the day.

Would really appreciate it if we can get it triaged soon, so I can go back to the [edX platform parent PR](https://github.com/edx/edx-platform/pull/16545).

2018-04-10 13:21 UTC, mulby commented
@OmarIthawi - I will review quickly when you are ready. Just let me know!

2018-04-10 15:58 UTC, OmarIthawi commented
Thanks @mulby!

I think the PR is ready. I also went through all of the previous comments to make sure all of them has been addressed. 

All of them was done, except that I wasn't sure what to do about the following comments.

[Comment no. 1](https://github.com/edx/edx-ace/pull/25#discussion_r175257206)

> We also may want to point people at the EMAIL_BACKEND setting so that they could test this using console output or a file or something:
> `EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`


[Comment no. 2](https://github.com/edx/edx-ace/pull/25#discussion_r175257332)

> I would also test the case when only a single channel implementation is registered for a particular channel type and we have to use the "six.next()" stuff.

2018-04-15 17:20 UTC, mulby reviewed
One minor change, otherwise looks good to me. I do think we need to fix the HTML email though before merging this.

I ran this locally and was able to send both transactional and non-transactional emails using the file channel and django email channel.

2018-04-15 17:20 UTC, mulby commented on edx_ace/channel/django_email.py
> +        from_address = message.options.get(u'from_address')
Optional, but I suggest changing this to:

```python
from_address = message.options.get(u'from_address')
if from_address is None:
    from_address = getattr(settings, 'ACE_CHANNEL_DJANGO_EMAIL_FROM_ADDRESS', None)
if from_address is None:
    raise FatalChannelDeliveryError(u'from_address must be included in message delivery options or configured via the setting ACE_CHANNEL_DJANGO_EMAIL_FROM_ADDRESS')
```

Since I suspect a particular installation will always want to use the same "from address" and not change it on a message by message basis.

2018-04-15 17:20 UTC, mulby commented on edx_ace/channel/django_email.py
> +                html_message=rendered_message.body_html,
You actually want this to be:

```python
TEMPLATE = u"""
<!DOCTYPE html>
<html>
    <head>
        {head_html}
    </head>
    <body>
        {body_html}
    </body>
</html>"""
rendered_template = TEMPLATE.format(
    head_html=rendered_message.head_html,
    body_html=rendered_message.body_html,
)
try:
    mail.send_mail(
        subject,
        rendered_message.body,
        from_address,
        [message.recipient.email_address],
        html_message=rendered_template,
    )
except SMTPException as e:
    LOG.exception(e)
    # ....
```

Since you need to also include the head HTML in the final HTML email.

2018-04-15 17:33 UTC, mulby commented on edx_ace/channel/django_email.py
> +        from_address = message.options.get(u'from_address')
Oh, right. I forgot we were using configuration_helpers to populate this. Nevermind!

2018-04-16 06:59 UTC, OmarIthawi commented on edx_ace/channel/django_email.py
> +        from_address = message.options.get(u'from_address')
@mulby No, you're right. We need to add a sane default. I've done that. Instead of failing silently, the message will be sent from a site-wide email address, while not perfect it's totally valid and will be sent!

2018-04-16 07:09 UTC, OmarIthawi commented on edx_ace/channel/django_email.py
> +                html_message=rendered_message.body_html,
@mulby Done.

2018-04-16 07:58 UTC, OmarIthawi commented
@mulby TravisCI is not doing very well. `caniusepython3` is having a trouble with the latest `pip`. Looks like we have some flaky dependencies despite the huge efforts on `pip-tools` :frowning_face:.

2018-04-16 17:47 UTC, mulby approved these changes

2018-04-16 17:47 UTC, mulby commented
We should increment the version number before merging, also looks like Travis is failing again.

2018-04-17 14:51 UTC, OmarIthawi commented
@mulby I tried to bump the versions but other requirements broke.

I'll try to do that in a separate PR. I'd really appreciate it if you can help with the version bump.

2018-04-18 19:23 UTC, OmarIthawi commented
@mulby It's ready. I'm all tears of joy!

2018-04-19 12:42 UTC, merged

2018-04-19 12:43 UTC, mulby commented
Great work @OmarIthawi - thanks again for your patience and producing such a high quality pull request!

2018-04-19 13:17 UTC, OmarIthawi commented
@mulby and @nasthagiri thank you so much for the detailed review and helping to get this PR done.

2018-04-20 19:58 UTC, mulby commented
@cpennington can you push 0.1.7 to pypi?

2018-04-23 05:44 UTC, OmarIthawi commented
Thanks @mulby. Isn't Travis supposed to do the push? Have I missed something in the process?

2018-04-24 11:12 UTC, nedbat commented
Someone has to create and push the 'v0.1.7' tag.  Travis only pushes to PyPI when a new tag is created.  I'll do it.

2018-04-25 07:43 UTC, OmarIthawi commented
Thanks @nedbat :smiley:

2018-04-25 07:45 UTC, OmarIthawi commented
As feedback. it would have been great to have write access here. It's been six [days since](https://github.com/edx/edx-ace/pull/25#issuecomment-382730988) the PR has been merged.