chore: update code owner details
openedx/edx-ace pull request #263
Opened 2024-02-26 09:55 UTC by zainab-amir

**Description:** Updates code owner info from 2u-vanguards to 2u-infinity

**JIRA:** https://2u-internal.atlassian.net/browse/VAN-1857

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Create a new release (can be done here https://github.com/edx/edx-ace/releases)
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2024-02-26 10:05 UTC, zainab-amir commented
Unable to add @openedx/2u-infinity as reviewers to this PR. Related issue created for axim https://github.com/openedx/axim-engineering/issues/1065

2024-02-26 14:38 UTC, hurtstotouchfire approved these changes

2024-02-26 14:39 UTC, hurtstotouchfire commented on catalog-info.yaml
> +  owner: group:edx-infinity
I thought that we changed all these legacy group names to 2u-something but Asad can fix it if this is wrong.

2024-02-26 16:07 UTC, arbrandes commented
I added the `2u-infinity` team to this repository with explicit write permissions, after which it became possible to add it as a reviewer.

2024-02-26 17:01 UTC, feanil requested changes

2024-02-26 17:01 UTC, feanil commented on catalog-info.yaml
> +  owner: group:edx-infinity
Agreed, this should be `2u-infinity` and if that team does not have the right people on it, we can update but it should be the team used moving forward.

2024-02-27 06:46 UTC, asadazam93 commented
@feanil can you make me (asadazam93) the maintainer of https://github.com/orgs/openedx/teams/2u-infinity? The team members are not up to date

2024-02-27 11:53 UTC, asadazam93 approved these changes

2024-02-27 14:39 UTC, feanil approved these changes

2024-02-27 14:41 UTC, merged