feat: added email sent signal to edx ace
openedx/edx-ace pull request #292
Opened 2024-07-22 08:09 UTC by AhtishamShahid

**Description:** Describe in a couple of sentence what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Create a new release (can be done here https://github.com/edx/edx-ace/releases)
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2024-07-22 18:43 UTC, OmarIthawi commented on edx_ace/ace.py
> +
Please remove this line to keep the commit more focused.

2024-07-22 18:45 UTC, OmarIthawi commented on edx_ace/delivery.py
> +from edx_ace.signals import ACE_EMAIL_SENT
@AhtishamShahid Should we use a Django signal here or a https://github.com/openedx/openedx-events and https://github.com/openedx/openedx-filters event?

This is more of discussion than a request. Please let me know what do you think?

2024-07-22 18:46 UTC, OmarIthawi commented on edx_ace/signals.py
> +ACE_EMAIL_SENT = Signal()
```suggestion
# signal to indicate that a message has been sent using ace
ACE_MESSAGE_SENT = Signal()
```

We support both Push notifications and email as message types among other types.

2024-08-02 08:17 UTC, asadazam93 approved these changes

2024-08-04 16:07 UTC, OmarIthawi requested changes
Please rename it. I still see the old `EMAIL` word in the diff.

2024-08-04 16:07 UTC, OmarIthawi commented on edx_ace/signals.py
> +ACE_EMAIL_SENT = Signal()
```suggestion
ACE_MESSAGE_SENT = Signal()
```

2024-08-05 08:12 UTC, AhtishamShahid commented on edx_ace/delivery.py
> +from edx_ace.signals import ACE_EMAIL_SENT
Hi,

We are not fundamentally changing the application behavior or flow , so using openedx-filters does not seem appropriate. However, openedx-events can work similarly to our current implementation. The use of global signals would be meaningful if we intended to handle that signal in other packages as well, but that is not the case at this time. Therefore, directly using Django signals makes more sense to me.

2024-08-06 07:03 UTC, muhammadadeeltajamul approved these changes
Have you thought of a way to check if an email fails to send?  I think they are also needed for tracking.

FYI:  I know the ticket scope is to generate event when email is send successfully.

2024-08-06 10:48 UTC, merged

2024-08-06 12:34 UTC, OmarIthawi reviewed
@AhtishamShahid I've sumitted a review already, but it seems that a bad internet connection got it lost.

I was surprised that it's been merged, but since my review was lost by GitHub, it's fine.

Would you mind checking the comment? It seems that we're sending the signal in cases where the message isn't sent.

Anyway, please ensure tests are added for the following cases:

 - Email is sent: ensure only one signal is sent.
 - Email sending fails: Ensure no signal is sent.
 - Email and Push notifications: Two signals are sent with appropriate `channel` parameter


```
ACE_MESSAGE_SENT.send(sender=channel, message=message)
```

2024-08-06 12:34 UTC, OmarIthawi commented on edx_ace/delivery.py
> +    ACE_MESSAGE_SENT.send(sender=channel, message=message)
Would you mind explaining the logic behind this line?

It seems to be added by mistake.

2024-08-06 12:35 UTC, OmarIthawi commented on edx_ace/delivery.py
> +    ACE_MESSAGE_SENT.send(sender=channel, message=message)
@muhammadadeeltajamul please check the review above and let me know when the notes can be addressed.

2024-08-07 10:14 UTC, AhtishamShahid commented
> @AhtishamShahid I've sumitted a review already, but it seems that a bad internet connection got it lost.
> 
> I was surprised that it's been merged, but since my review was lost by GitHub, it's fine.
> 
> Would you mind checking the comment? It seems that we're sending the signal in cases where the message isn't sent.
> 
> Anyway, please ensure tests are added for the following cases:
> 
> * Email is sent: ensure only one signal is sent.
> * Email sending fails: Ensure no signal is sent.
> * Email and Push notifications: Two signals are sent with appropriate `channel` parameter
> 
> ```
> ACE_MESSAGE_SENT.send(sender=channel, message=message)
> ```

Create a PR with these changes https://github.com/openedx/edx-ace/pull/296